version: '3.7'

services:
  redis:
    image: redis:5-alpine
    volumes:
      - redis_data:/data

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 32768:5432
    environment:
      - POSTGRES_USER=wind_app
      - POSTGRES_PASSWORD=6d9hVwItF9A33hc
      - POSTGRES_DB=wind_app_db

  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: >
      sh -c "python manage.py wait_for_database &&
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./wind_app:/app_code/wind_app
      - ./api:/app_code/api
      - ./wind_test:/app_code/wind_test
      - ./templates:/app_code/templates
      - static_volume:/app_code/staticfiles
      - media_volume:/app_code/media
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db

  celery:
    build: .
    command: celery worker --app=wind_app --loglevel=debug --autoscale=10,4
    volumes:
      - .:/usr/src/app
    env_file:
      - ./.env
    depends_on:
      - web
      - redis

#  celery-beat:
#    build: .
#    command: >
#      sh -c "celery beat --app=wind_app --loglevel=debug --max-interva=30"
#    volumes:
#      - .:/usr/src/app
#    env_file:
#      - ./.env
#    depends_on:
#      - db
#      - web
#      - redis

  dashboard:
    build: .
    command: [ "sh", "-c", "flower -A wind_app --port=5555 --broker=$${CELERY_BACKEND} --basic_auth=$${FLOWER_USER}:$${FLOWER_PASSWORD}" ]
    ports:
      - 5555:5555
    env_file:
      - ./.env
    depends_on:
      - web
      - redis
      - celery

volumes:
  redis_data:
  postgres_data:
  static_volume:
  media_volume:
